COMMENT ON TYPE "FamilyMode" IS '家庭运行模式枚举：LOCAL 为单机模式，CLOUD 为云端模式。';
COMMENT ON TYPE "AccountStatus" IS '家庭统一账号状态枚举。';
COMMENT ON TYPE "MemberStatus" IS '家庭成员状态枚举。';
COMMENT ON TYPE "TaskType" IS '家务规则分类枚举：LIGHT、CORE、EPIC。';
COMMENT ON TYPE "TaskRuleStatus" IS '家务规则状态枚举。';
COMMENT ON TYPE "EventStatus" IS '事件状态枚举：PENDING 待确认，CONFIRMED 已确认，REVERTED 已撤销。';
COMMENT ON TYPE "VerdictSource" IS '判决内容来源枚举：AI 或本地降级模板。';
COMMENT ON TYPE "VerdictStatus" IS '判决生成状态枚举。';
COMMENT ON TYPE "AuditAction" IS '审计日志动作类型枚举。';

COMMENT ON TABLE "family_accounts" IS '家庭统一账号表，用于云端模式登录。';
COMMENT ON COLUMN "family_accounts"."id" IS '账号主键 UUID。';
COMMENT ON COLUMN "family_accounts"."account_name" IS '家庭统一登录账号名。';
COMMENT ON COLUMN "family_accounts"."password_hash" IS '密码哈希值。';
COMMENT ON COLUMN "family_accounts"."password_algo" IS '密码哈希算法标识，例如 scrypt-v1。';
COMMENT ON COLUMN "family_accounts"."status" IS '账号状态。';
COMMENT ON COLUMN "family_accounts"."last_login_at" IS '最近一次成功登录时间。';
COMMENT ON COLUMN "family_accounts"."created_at" IS '账号创建时间。';
COMMENT ON COLUMN "family_accounts"."updated_at" IS '账号最后更新时间。';

COMMENT ON TABLE "families" IS '家庭空间主体表，一个家庭账号对应一个家庭空间。';
COMMENT ON COLUMN "families"."id" IS '家庭主键 UUID。';
COMMENT ON COLUMN "families"."account_id" IS '关联家庭统一账号 ID。';
COMMENT ON COLUMN "families"."name" IS '家庭名称或空间名称。';
COMMENT ON COLUMN "families"."mode" IS '当前家庭运行模式，云端记录通常为 CLOUD。';
COMMENT ON COLUMN "families"."timezone" IS '家庭时区，用于计算 week_id 和时间展示。';
COMMENT ON COLUMN "families"."current_week_id" IS '当前周标识，例如 2026-W17。';
COMMENT ON COLUMN "families"."version" IS '家庭配置版本号，用于后续配置同步或乐观并发控制。';
COMMENT ON COLUMN "families"."created_at" IS '家庭空间创建时间。';
COMMENT ON COLUMN "families"."updated_at" IS '家庭空间最后更新时间。';

COMMENT ON TABLE "family_sessions" IS '家庭登录会话表，用于 refresh token 和设备会话管理。';
COMMENT ON COLUMN "family_sessions"."id" IS '会话主键 UUID。';
COMMENT ON COLUMN "family_sessions"."family_id" IS '所属家庭 ID。';
COMMENT ON COLUMN "family_sessions"."refresh_token_hash" IS '刷新令牌哈希值，不直接存储原始 token。';
COMMENT ON COLUMN "family_sessions"."device_label" IS '客户端设备标识，例如 iPad-living-room。';
COMMENT ON COLUMN "family_sessions"."user_agent" IS '发起会话时记录的 User-Agent。';
COMMENT ON COLUMN "family_sessions"."expires_at" IS '会话过期时间。';
COMMENT ON COLUMN "family_sessions"."last_used_at" IS '最近一次使用该会话的时间。';
COMMENT ON COLUMN "family_sessions"."created_at" IS '会话创建时间。';

COMMENT ON TABLE "members" IS '家庭成员表。';
COMMENT ON COLUMN "members"."id" IS '成员主键 UUID。';
COMMENT ON COLUMN "members"."family_id" IS '所属家庭 ID。';
COMMENT ON COLUMN "members"."nickname" IS '成员昵称。';
COMMENT ON COLUMN "members"."avatar_type" IS '头像类型，例如 image、emoji、initial。';
COMMENT ON COLUMN "members"."avatar_url" IS '图片头像地址。';
COMMENT ON COLUMN "members"."avatar_value" IS 'emoji 或首字母等轻量头像值。';
COMMENT ON COLUMN "members"."card_color" IS '成员卡片配色 token。';
COMMENT ON COLUMN "members"."sort_order" IS '成员显示排序。';
COMMENT ON COLUMN "members"."status" IS '成员状态。';
COMMENT ON COLUMN "members"."joined_week_id" IS '成员加入家庭时所在周。';
COMMENT ON COLUMN "members"."left_week_id" IS '成员离开家庭时所在周。';
COMMENT ON COLUMN "members"."created_at" IS '成员创建时间。';
COMMENT ON COLUMN "members"."updated_at" IS '成员最后更新时间。';

COMMENT ON TABLE "task_rules" IS '家务规则项表，定义标签、分类与默认分值。';
COMMENT ON COLUMN "task_rules"."id" IS '规则主键 UUID。';
COMMENT ON COLUMN "task_rules"."family_id" IS '所属家庭 ID。';
COMMENT ON COLUMN "task_rules"."task_type" IS '规则分类。';
COMMENT ON COLUMN "task_rules"."label" IS '规则标签名称。';
COMMENT ON COLUMN "task_rules"."score_delta" IS '该规则默认分值。';
COMMENT ON COLUMN "task_rules"."sort_order" IS '规则显示排序。';
COMMENT ON COLUMN "task_rules"."is_pinned" IS '是否为推荐或置顶规则。';
COMMENT ON COLUMN "task_rules"."status" IS '规则状态。';
COMMENT ON COLUMN "task_rules"."created_at" IS '规则创建时间。';
COMMENT ON COLUMN "task_rules"."updated_at" IS '规则最后更新时间。';

COMMENT ON TABLE "task_events" IS '家务打卡事件事实表，是排行、日志、归档和判决的核心事实来源。';
COMMENT ON COLUMN "task_events"."id" IS '服务端事件主键 UUID。';
COMMENT ON COLUMN "task_events"."family_id" IS '所属家庭 ID。';
COMMENT ON COLUMN "task_events"."member_id" IS '触发事件的成员 ID。';
COMMENT ON COLUMN "task_events"."task_rule_id" IS '关联规则 ID，允许为空以兼容历史规则变化。';
COMMENT ON COLUMN "task_events"."week_id" IS '事件所属周标识。';
COMMENT ON COLUMN "task_events"."task_type_snapshot" IS '事件发生时的规则分类快照。';
COMMENT ON COLUMN "task_events"."task_label_snapshot" IS '事件发生时的规则标签快照。';
COMMENT ON COLUMN "task_events"."score_delta_snapshot" IS '事件发生时的分值快照。';
COMMENT ON COLUMN "task_events"."member_nickname_snapshot" IS '事件发生时的成员昵称快照。';
COMMENT ON COLUMN "task_events"."client_event_id" IS '前端生成的幂等事件 ID。';
COMMENT ON COLUMN "task_events"."undo_token" IS '撤销事件时使用的凭证 token。';
COMMENT ON COLUMN "task_events"."undo_expires_at" IS '撤销窗口截止时间。';
COMMENT ON COLUMN "task_events"."status" IS '事件状态：待确认、已确认或已撤销。';
COMMENT ON COLUMN "task_events"."reverted_at" IS '事件被撤销的时间。';
COMMENT ON COLUMN "task_events"."created_at" IS '事件创建时间。';
COMMENT ON COLUMN "task_events"."confirmed_at" IS '事件从待确认转为正式确认的时间。';

COMMENT ON TABLE "weekly_archives" IS '每周归档快照表，保存周级汇总结果。';
COMMENT ON COLUMN "weekly_archives"."id" IS '周归档主键 UUID。';
COMMENT ON COLUMN "weekly_archives"."family_id" IS '所属家庭 ID。';
COMMENT ON COLUMN "weekly_archives"."week_id" IS '归档对应周标识。';
COMMENT ON COLUMN "weekly_archives"."start_at" IS '该周开始时间。';
COMMENT ON COLUMN "weekly_archives"."end_at" IS '该周结束时间。';
COMMENT ON COLUMN "weekly_archives"."total_events" IS '该周正式确认事件总数。';
COMMENT ON COLUMN "weekly_archives"."total_score" IS '该周总分。';
COMMENT ON COLUMN "weekly_archives"."summary_json" IS '该周归档聚合快照 JSON。';
COMMENT ON COLUMN "weekly_archives"."created_at" IS '归档创建时间。';

COMMENT ON TABLE "verdict_records" IS 'AI 判决结果表，保存正式判决或降级模板输出。';
COMMENT ON COLUMN "verdict_records"."id" IS '判决记录主键 UUID。';
COMMENT ON COLUMN "verdict_records"."family_id" IS '所属家庭 ID。';
COMMENT ON COLUMN "verdict_records"."week_id" IS '判决对应周标识。';
COMMENT ON COLUMN "verdict_records"."archive_id" IS '关联的周归档 ID。';
COMMENT ON COLUMN "verdict_records"."persona" IS '生成判决时使用的人设。';
COMMENT ON COLUMN "verdict_records"."style_profile_json" IS '生成判决时使用的风格配置快照。';
COMMENT ON COLUMN "verdict_records"."source" IS '判决内容来源。';
COMMENT ON COLUMN "verdict_records"."status" IS '判决生成状态。';
COMMENT ON COLUMN "verdict_records"."content" IS '判决正文内容。';
COMMENT ON COLUMN "verdict_records"."input_snapshot_json" IS '生成判决时的输入数据快照。';
COMMENT ON COLUMN "verdict_records"."safety_status" IS '内容安全检查结果。';
COMMENT ON COLUMN "verdict_records"."generated_at" IS '判决生成时间。';

COMMENT ON TABLE "preferences" IS '家庭级偏好设置表，控制公共屏和控制台风格。';
COMMENT ON COLUMN "preferences"."id" IS '偏好设置主键 UUID。';
COMMENT ON COLUMN "preferences"."family_id" IS '所属家庭 ID，一家仅一条记录。';
COMMENT ON COLUMN "preferences"."default_fullscreen" IS '是否默认全屏展示。';
COMMENT ON COLUMN "preferences"."sound_enabled" IS '是否启用音效。';
COMMENT ON COLUMN "preferences"."motion_enabled" IS '是否启用动效。';
COMMENT ON COLUMN "preferences"."font_scale" IS '字号档位。';
COMMENT ON COLUMN "preferences"."theme_style" IS '主题风格标识。';
COMMENT ON COLUMN "preferences"."log_speed" IS '公开日志滚动速度。';
COMMENT ON COLUMN "preferences"."card_density" IS '成员卡片密度。';
COMMENT ON COLUMN "preferences"."idle_reminder_enabled" IS '是否启用沉寂提醒。';
COMMENT ON COLUMN "preferences"."verdict_persona" IS '默认判决人设。';
COMMENT ON COLUMN "preferences"."verdict_toxicity_level" IS '毒舌强度，范围通常为 0 到 10。';
COMMENT ON COLUMN "preferences"."allow_attack" IS '是否允许攻击式表达。';
COMMENT ON COLUMN "preferences"."allow_humiliation" IS '是否允许羞辱式表达。';
COMMENT ON COLUMN "preferences"."allow_labeling" IS '是否允许贴标签式表达。';
COMMENT ON COLUMN "preferences"."updated_at" IS '偏好设置最后更新时间。';

COMMENT ON TABLE "audit_logs" IS '控制台高风险操作与配置变更审计日志表。';
COMMENT ON COLUMN "audit_logs"."id" IS '审计日志主键 UUID。';
COMMENT ON COLUMN "audit_logs"."family_id" IS '所属家庭 ID。';
COMMENT ON COLUMN "audit_logs"."action" IS '审计动作类型。';
COMMENT ON COLUMN "audit_logs"."operator_account_id" IS '执行操作的账号 ID。';
COMMENT ON COLUMN "audit_logs"."target_type" IS '被操作对象类型。';
COMMENT ON COLUMN "audit_logs"."target_id" IS '被操作对象 ID。';
COMMENT ON COLUMN "audit_logs"."before_json" IS '变更前快照。';
COMMENT ON COLUMN "audit_logs"."after_json" IS '变更后快照。';
COMMENT ON COLUMN "audit_logs"."created_at" IS '操作发生时间。';
